import { useState, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { gql } from '@apollo/client';
import client from '../client';
import { useQuery } from '@apollo/client';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [name, setName] = useState('');

  useEffect(() => {
    //usdc 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
    //tusd 0xdAC17F958D2ee523a2206206994597C13D831ec7
    const fetchGql = async () => {
      const { data } = await client.query({
        query: gql`
            query GetTokens {
              contracts(chainId: 1) {
                SHIB {
                  decimals
                  name
                  totalSupply
                  balanceOf(_owner: "0x5a52e96bacdabb82fd05763e25335261b270efcb")
                }
                ERC20(
                  addresses: [
                    "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
                    "0xdAC17F958D2ee523a2206206994597C13D831ec7"
                  ]
                ) {
                  name
                  totalSupply
                }
              }
            }
          `,
      });
      console.log("data", data);
    }
    fetchGql();
  }, [])

  const GET_TOKEN = gql`
    query GetToken {
      contracts(chainId: 1) {
        ERC20(
          addresses: [
            "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
            "0xdAC17F958D2ee523a2206206994597C13D831ec7"
          ]
        ) {
          name
          totalSupply
        }
      }
    }
  `;
  const { loading, error, data } = useQuery(
    GET_TOKEN
  );

  if (loading) {
    return <p>Loading...</p>;
  }
  if (error) {
    return `Error! ${error.message}`;
  }

  const handleSubmit = (e: any) => {

    e.preventDefault();

    console.log(`Form submitted, ${name}`);

  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.code}>
          {data.contracts.ERC20.map((token: any)=> (
            <div key={`token-${token.name}`}>
              <p>
                {token.name}: {token.totalSupply}
              </p>
            </div>
          ))}
        </div>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <form onSubmit={handleSubmit}>
            <input onChange={(e) => setName(e.target.value)} value={name}></input>
            <button type='submit'>Click to submit</button>
          </form>
        </div>
      </main>
    </>
  )
}
